### PR TITLE
Fixes #5 added subscribe, unsubscribe and all end points

### LINKED ISSUE #5: Create dynamic end points for the vaccination availability for different pincodes. (See description)
1. http://localhost:PORT/subscribe?pincode=PINCODE&email=EMAIL should start listeners to listen for vaccination availability at the pincode PINCODE and send email at EMAIL

You might need to create some sort of global reference to different listeners for different pincodes and for those listeners.

eg:  
```js 
let listeners = {
    "pincode1" : {
        interval: intervalReference,    // to clear the interval in future if required
        emails:[email1, email2]
    },
    //pincode2: {...},
    //pincode3: {...}
}
```

(feel free to implement something different than this example)

2. http://localhost:PORT/unsubscribe?email=EMAIL should remove the email from receiving the email. Also clear the interval if no emails are associated with it.

3. http://localhost:PORT/all should return the all listeners and the emails associated with it

### PR DESCRIPTION
**Pull request by XDRAGON2002**
Fixes #5 
Added dynamic end points and mailing.

### CODE REVIEW

**Review by TheNinza — COMMENTED** [review]
hey @XDRAGON2002,
 Currently the code clears the interval when vaccination is available in any pincode (line 69)... 
The current approach relies on only one interval... the interval keeps on running even if there are no pincodes or emails available to look for. A better approach will be to make separate interval for separate pincodes and clearing them when vaccination is available...

**Comment by XDRAGON2002** [comment]
@TheNinza 
Oh okay got it, I'll make the changes and make commits to this PR.

**Comment by XDRAGON2002** [comment]
@TheNinza Updated the PR.

**Review by TheNinza — COMMENTED** [review]
currently you are first looping over the email array and then checking if the available slots have length greater than 0 (line 64). You should first check if slots are present then loop over emails to send mail

**Comment by XDRAGON2002** [comment]
@TheNinza 
Made the latest update and commited.

**Comment by TheNinza** [comment]
hey @XDRAGON2002 , sorry for the delay from my side. I will test the code tomorrow and then merge it.

**Comment by XDRAGON2002** [comment]
Sure, no problem.

**Review by TheNinza — APPROVED** [review]
Good work @XDRAGON2002 , merging. Hope you enjoyed this problem

**Comment by XDRAGON2002** [comment]
@TheNinza The issue was actually a great issue, thanks for letting me contribute !

**Pull request merged**
